-- Generated by generate_starbucks_db.py. Do not edit by hand.
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `regions`;
CREATE TABLE regions (
        region_id INTEGER PRIMARY KEY,
        region_name VARCHAR(255) NOT NULL,
        regional_director VARCHAR(255)
    );

DROP TABLE IF EXISTS `stores`;
CREATE TABLE stores (
        store_id INTEGER PRIMARY KEY,
        store_name VARCHAR(255),
        city VARCHAR(255), state VARCHAR(255), country VARCHAR(255),
        region VARCHAR(255),
        store_type VARCHAR(255),
        open_date VARCHAR(255),
        square_feet INTEGER,
        manager_id INTEGER
    );

DROP TABLE IF EXISTS `employees`;
CREATE TABLE employees (
        employee_id INTEGER PRIMARY KEY,
        store_id INTEGER,
        first_name VARCHAR(255), last_name VARCHAR(255),
        role VARCHAR(255),
        hire_date VARCHAR(255),
        hourly_rate DECIMAL(12,2),
        status VARCHAR(255),
        performance_rating INTEGER,
        FOREIGN KEY (store_id) REFERENCES stores(store_id)
    );

DROP TABLE IF EXISTS `products`;
CREATE TABLE products (
        product_id INTEGER PRIMARY KEY,
        product_name VARCHAR(255),
        category VARCHAR(255),
        subcategory VARCHAR(255),
        unit_price DECIMAL(12,2),
        cost DECIMAL(12,2),
        is_seasonal INTEGER,
        launch_date VARCHAR(255)
    );

DROP TABLE IF EXISTS `suppliers`;
CREATE TABLE suppliers (
        supplier_id INTEGER PRIMARY KEY,
        supplier_name VARCHAR(255),
        category VARCHAR(255),
        country VARCHAR(255),
        lead_time_days INTEGER,
        reliability_score INTEGER,
        contract_start VARCHAR(255),
        contract_end VARCHAR(255)
    );

DROP TABLE IF EXISTS `customers`;
CREATE TABLE customers (
        customer_id INTEGER PRIMARY KEY,
        first_name VARCHAR(255), last_name VARCHAR(255),
        email VARCHAR(255),
        city VARCHAR(255), state VARCHAR(255),
        join_date VARCHAR(255),
        rewards_tier VARCHAR(255),
        lifetime_spend DECIMAL(12,2),
        visits_last_90_days INTEGER
    );

DROP TABLE IF EXISTS `daily_sales`;
CREATE TABLE daily_sales (
        sale_date VARCHAR(255),
        store_id INTEGER,
        total_revenue DECIMAL(12,2),
        total_transactions INTEGER,
        avg_ticket_size DECIMAL(12,2),
        mobile_order_pct DECIMAL(12,2),
        FOREIGN KEY (store_id) REFERENCES stores(store_id)
    );

DROP TABLE IF EXISTS `product_sales`;
CREATE TABLE product_sales (
        week_start VARCHAR(255),
        store_id INTEGER,
        product_id INTEGER,
        quantity_sold INTEGER,
        revenue DECIMAL(12,2),
        discount_amount DECIMAL(12,2),
        FOREIGN KEY (store_id) REFERENCES stores(store_id),
        FOREIGN KEY (product_id) REFERENCES products(product_id)
    );

DROP TABLE IF EXISTS `customer_orders`;
CREATE TABLE customer_orders (
        order_id INTEGER PRIMARY KEY,
        customer_id INTEGER,
        store_id INTEGER,
        order_date VARCHAR(255),
        order_total DECIMAL(12,2),
        items_count INTEGER,
        payment_method VARCHAR(255),
        is_mobile_order INTEGER,
        FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
        FOREIGN KEY (store_id) REFERENCES stores(store_id)
    );

DROP TABLE IF EXISTS `inventory`;
CREATE TABLE inventory (
        record_id INTEGER PRIMARY KEY AUTO_INCREMENT,
        record_date VARCHAR(255),
        store_id INTEGER,
        item_name VARCHAR(255),
        category VARCHAR(255),
        quantity_on_hand INTEGER,
        reorder_point INTEGER,
        unit_cost DECIMAL(12,2),
        supplier_id INTEGER,
        FOREIGN KEY (store_id) REFERENCES stores(store_id),
        FOREIGN KEY (supplier_id) REFERENCES suppliers(supplier_id)
    );

DROP TABLE IF EXISTS `customer_feedback`;
CREATE TABLE customer_feedback (
        feedback_id INTEGER PRIMARY KEY,
        store_id INTEGER,
        customer_id INTEGER,
        feedback_date VARCHAR(255),
        rating INTEGER,
        category VARCHAR(255),
        comment VARCHAR(255),
        FOREIGN KEY (store_id) REFERENCES stores(store_id),
        FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
    );

DROP TABLE IF EXISTS `marketing_campaigns`;
CREATE TABLE marketing_campaigns (
        campaign_id INTEGER PRIMARY KEY,
        campaign_name VARCHAR(255),
        channel VARCHAR(255),
        start_date VARCHAR(255), end_date VARCHAR(255),
        budget DECIMAL(12,2),
        impressions INTEGER,
        clicks INTEGER,
        conversions INTEGER,
        revenue_attributed DECIMAL(12,2)
    );

DROP TABLE IF EXISTS `loyalty_transactions`;
CREATE TABLE loyalty_transactions (
        transaction_id INTEGER PRIMARY KEY,
        customer_id INTEGER,
        transaction_date VARCHAR(255),
        stars_earned INTEGER,
        stars_redeemed INTEGER,
        reward_type VARCHAR(255),
        transaction_amount DECIMAL(12,2),
        FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
    );

DROP TABLE IF EXISTS `labor_schedule`;
CREATE TABLE labor_schedule (
        schedule_id INTEGER PRIMARY KEY,
        store_id INTEGER,
        employee_id INTEGER,
        shift_date VARCHAR(255),
        shift_start VARCHAR(255),
        shift_end VARCHAR(255),
        hours_worked DECIMAL(12,2),
        is_overtime INTEGER,
        FOREIGN KEY (store_id) REFERENCES stores(store_id),
        FOREIGN KEY (employee_id) REFERENCES employees(employee_id)
    );

DROP TABLE IF EXISTS `financial_summary`;
CREATE TABLE financial_summary (
        month VARCHAR(255),
        store_id INTEGER,
        revenue DECIMAL(12,2),
        cogs DECIMAL(12,2),
        labor_cost DECIMAL(12,2),
        rent DECIMAL(12,2),
        utilities DECIMAL(12,2),
        marketing_cost DECIMAL(12,2),
        other_expenses DECIMAL(12,2),
        net_profit DECIMAL(12,2),
        FOREIGN KEY (store_id) REFERENCES stores(store_id)
    );

DROP TABLE IF EXISTS `store_traffic`;
CREATE TABLE store_traffic (
        record_date VARCHAR(255),
        store_id INTEGER,
        hour_block VARCHAR(255),
        foot_traffic INTEGER,
        conversion_rate DECIMAL(12,2),
        FOREIGN KEY (store_id) REFERENCES stores(store_id)
    );

DROP TABLE IF EXISTS `waste_log`;
CREATE TABLE waste_log (
        log_id INTEGER PRIMARY KEY,
        log_date VARCHAR(255),
        store_id INTEGER,
        product_id INTEGER,
        quantity_wasted INTEGER,
        waste_reason VARCHAR(255),
        estimated_cost DECIMAL(12,2),
        FOREIGN KEY (store_id) REFERENCES stores(store_id),
        FOREIGN KEY (product_id) REFERENCES products(product_id)
    );

DROP TABLE IF EXISTS `delivery_orders`;
CREATE TABLE delivery_orders (
        order_id INTEGER PRIMARY KEY,
        customer_id INTEGER,
        store_id INTEGER,
        order_date VARCHAR(255),
        delivery_partner VARCHAR(255),
        order_total DECIMAL(12,2),
        delivery_fee DECIMAL(12,2),
        delivery_time_min INTEGER,
        customer_rating DECIMAL(12,2),
        FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
        FOREIGN KEY (store_id) REFERENCES stores(store_id)
    );

DROP TABLE IF EXISTS `training_records`;
CREATE TABLE training_records (
        record_id INTEGER PRIMARY KEY,
        employee_id INTEGER,
        training_name VARCHAR(255),
        training_type VARCHAR(255),
        completion_date VARCHAR(255),
        score DECIMAL(12,2),
        duration_hours DECIMAL(12,2),
        FOREIGN KEY (employee_id) REFERENCES employees(employee_id)
    );

DROP TABLE IF EXISTS `regional_performance`;
CREATE TABLE regional_performance (
        region VARCHAR(255),
        quarter VARCHAR(255),
        total_revenue DECIMAL(12,2),
        store_count INTEGER,
        avg_revenue_per_store DECIMAL(12,2),
        yoy_growth_pct DECIMAL(12,2),
        customer_satisfaction_avg DECIMAL(12,2),
        employee_turnover_pct DECIMAL(12,2)
    );

DROP TABLE IF EXISTS `menu_pricing_history`;
CREATE TABLE menu_pricing_history (
        price_id INTEGER PRIMARY KEY,
        product_id INTEGER,
        effective_date VARCHAR(255),
        old_price DECIMAL(12,2),
        new_price DECIMAL(12,2),
        change_reason VARCHAR(255),
        FOREIGN KEY (product_id) REFERENCES products(product_id)
    );

CREATE INDEX idx_daily_sales_store ON daily_sales(store_id);
CREATE INDEX idx_daily_sales_date ON daily_sales(sale_date);
CREATE INDEX idx_product_sales_product ON product_sales(product_id);
CREATE INDEX idx_product_sales_store ON product_sales(store_id);
CREATE INDEX idx_labor_schedule_store ON labor_schedule(store_id);
CREATE INDEX idx_labor_schedule_employee ON labor_schedule(employee_id);
CREATE INDEX idx_customer_orders_customer ON customer_orders(customer_id);
CREATE INDEX idx_customer_orders_store ON customer_orders(store_id);
CREATE INDEX idx_financial_summary_store ON financial_summary(store_id);
CREATE INDEX idx_financial_summary_month ON financial_summary(month);
CREATE INDEX idx_inventory_store ON inventory(store_id);
CREATE INDEX idx_waste_log_store ON waste_log(store_id);
CREATE INDEX idx_delivery_orders_store ON delivery_orders(store_id);
CREATE INDEX idx_customer_feedback_store ON customer_feedback(store_id);
CREATE INDEX idx_store_traffic_store ON store_traffic(store_id);
CREATE INDEX idx_loyalty_transactions_customer ON loyalty_transactions(customer_id);

SET FOREIGN_KEY_CHECKS=1;
